"""add_collection_to_oauth

Revision ID: fb06c7171ada
Revises: 006
Create Date: 2025-11-23 20:48:06.022631

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

# revision identifiers, used by Alembic.
revision: str = "fb06c7171ada"
down_revision: Union[str, None] = "006"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("oauth_accounts", schema=None) as batch_op:
        batch_op.add_column(sa.Column("collection_name", sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("oauth_accounts", schema=None) as batch_op:
        batch_op.drop_column("collection_name")
    # ### end Alembic commands ###
